import expect from 'expect';
import elementRoleMap from '../../src/elementRoleMap';

describe('domRolesMap', function () {
  it('should be a Map', function () {
    expect(elementRoleMap instanceof Map).toBe(true);
  });
  it('should have specific items', function () {
    expect(Array.from(elementRoleMap.entries())).toEqual(
      expect.arrayContaining(
        [
          [{"name": "menuitem"}, new Set("command", "menuitem")],
          [{"name": "rel"}, new Set("roletype")],
          [{"name": "article"}, new Set("article")],
          [{"constraints": ["direct descendant of document"], "name": "header"}, new Set("banner")],
          [{"attributes": [{"constraints": ["set"], "name": "aria-pressed"}, {"name": "type", "value": "checkbox"}], "name": "input"}, new Set("button")],
          [{"attributes": [{"name": "aria-expanded", "value": "false"}], "name": "summary"}, new Set("button")],
          [{"attributes": [{"name": "aria-expanded", "value": "true"}], "constraints": ["direct descendant of details element with the open attribute defined"], "name": "summary"}, new Set("button")],
          [{"attributes": [{"name": "type", "value": "button"}], "name": "input"}, new Set("button")],
          [{"attributes": [{"name": "type", "value": "image"}], "name": "input"}, new Set("button")],
          [{"attributes": [{"name": "type", "value": "reset"}], "name": "input"}, new Set("button")],
          [{"attributes": [{"name": "type", "value": "submit"}], "name": "input"}, new Set("button")],
          [{"name": "button"}, new Set("button")],
          [{"constraints": ["descendant of table"], "name": "td"}, new Set("cell")],
          [{"attributes": [{"name": "type", "value": "checkbox"}], "name": "input"}, new Set("checkbox")],
          [{"name": "th"}, new Set("columnheader")],
          [{"attributes": [{"constraints": ["set"], "name": "list"}, {"name": "type", "value": "email"}], "name": "input"}, new Set("combobox")],
          [{"attributes": [{"constraints": ["set"], "name": "list"}, {"name": "type", "value": "search"}], "name": "input"}, new Set("combobox")],
          [{"attributes": [{"constraints": ["set"], "name": "list"}, {"name": "type", "value": "tel"}], "name": "input"}, new Set("combobox")],
          [{"attributes": [{"constraints": ["set"], "name": "list"}, {"name": "type", "value": "text"}], "name": "input"}, new Set("combobox")],
          [{"attributes": [{"constraints": ["set"], "name": "list"}, {"name": "type", "value": "url"}], "name": "input"}, new Set("combobox")],
          [{"attributes": [{"constraints": ["set"], "name": "list"}, {"name": "type", "value": "url"}], "name": "input"}, new Set("combobox")],
          [{"attributes": [{"constraints": ["undefined"], "name": "multiple"}, {"constraints": ["undefined"], "name": "size"}], "name": "select"}, new Set("combobox")],
          [{"attributes": [{"constraints": ["undefined"], "name": "multiple"}, {"name": "size", "value": 1}], "name": "select"}, new Set("combobox")],
          [{"name": "aside"}, new Set("complementary")],
          [{"constraints": ["direct descendant of document"], "name": "footer"}, new Set("contentinfo")],
          [{"name": "dd"}, new Set("definition")],
          [{"name": "dialog"}, new Set("dialog")],
          [{"name": "body"}, new Set("document")],
          [{"name": "figure"}, new Set("figure")],
          [{"attributes": [{"constraints": ["set"], "name": "aria-label"}], "name": "form"}, new Set("form")],
          [{"attributes": [{"constraints": ["set"], "name": "aria-labelledby"}], "name": "form"}, new Set("form")],
          [{"attributes": [{"constraints": ["set"], "name": "name"}], "name": "form"}, new Set("form")],
          [{"name": "span"}, new Set("generic")],
          [{"name": "div"}, new Set("generic")],
          [{"attributes": [{"name": "role", "value": "grid"}], "name": "table"}, new Set("grid")],
          [{"attributes": [{"name": "role", "value": "gridcell"}], "name": "td"}, new Set("gridcell")],
          [{"name": "details"}, new Set("group")],
          [{"name": "fieldset"}, new Set("group")],
          [{"name": "optgroup"}, new Set("group")],
          [{"name": "h1"}, new Set("heading")],
          [{"name": "h2"}, new Set("heading")],
          [{"name": "h3"}, new Set("heading")],
          [{"name": "h4"}, new Set("heading")],
          [{"name": "h5"}, new Set("heading")],
          [{"name": "h6"}, new Set("heading")],
          [{"attributes": [{"constraints": ["set"], "name": "alt"}], "name": "img"}, new Set("img")],
          [{"attributes": [{"constraints": ["undefined"], "name": "alt"}], "name": "img"}, new Set("img")],
          [{"attributes": [{"name": "href"}], "name": "a"}, new Set("link")],
          [{"attributes": [{"name": "href"}], "name": "area"}, new Set("link")],
          [{"attributes": [{"name": "href"}], "name": "link"}, new Set("link")],
          [{"name": "menu"}, new Set("list")],
          [{"name": "ol"}, new Set("list")],
          [{"name": "ul"}, new Set("list")],
          [{"attributes": [{"constraints": [">1"], "name": "size"}, {"name": "multiple"}], "name": "select"}, new Set("listbox")],
          [{"attributes": [{"constraints": [">1"], "name": "size"}], "name": "select"}, new Set("listbox")],
          [{"attributes": [{"name": "multiple"}], "name": "select"}, new Set("listbox")],
          [{"name": "datalist"}, new Set("listbox")],
          [{"constraints": ["direct descendant of ol, ul or menu"], "name": "li"}, new Set("listitem")],
          [{"name": "main"}, new Set("main")],
          [{"name": "math"}, new Set("math")],
          [{"name": "menuitem"}, new Set("command", "menuitem")],
          [{"name": "nav"}, new Set("navigation")],
          [{"name": "option"}, new Set("option")],
          [{"name": "progress"}, new Set("progressbar")],
          [{"attributes": [{"name": "type", "value": "radio"}], "name": "input"}, new Set("radio")],
          [{"attributes": [{"constraints": ["set"], "name": "aria-label"}], "name": "section"}, new Set("region")],
          [{"attributes": [{"constraints": ["set"], "name": "aria-labelledby"}], "name": "section"}, new Set("region")],
          [{"name": "frame"}, new Set("region")],
          [{"name": "tr"}, new Set("row")],
          [{"name": "tbody"}, new Set("rowgroup")],
          [{"name": "tfoot"}, new Set("rowgroup")],
          [{"name": "thead"}, new Set("rowgroup")],
          [{"attributes": [{"name": "scope", "value": "row"}], "name": "th"}, new Set("rowheader")],
          [{"attributes": [{"constraints": ["undefined"], "name": "list"}, {"name": "type", "value": "search"}], "name": "input"}, new Set("searchbox")],
          [{"name": "hr"}, new Set("separator")],
          [{"attributes": [{"name": "type", "value": "range"}], "name": "input"}, new Set("slider")],
          [{"attributes": [{"name": "type", "value": "number"}], "name": "input"}, new Set("spinbutton")],
          [{"name": "output"}, new Set("status")],
          [{"name": "table"}, new Set("table")],
          [{"name": "dfn"}, new Set("term")],
          [{"name": "dt"}, new Set("term")],
          [{"attributes": [{"constraints": ["undefined"], "name": "type"}, {"constraints": ["undefined"], "name": "list"}], "name": "input"}, new Set("textbox")],
          [{"attributes": [{"constraints": ["undefined"], "name": "list"}, {"name": "type", "value": "email"}], "name": "input"}, new Set("textbox")],
          [{"attributes": [{"constraints": ["undefined"], "name": "list"}, {"name": "type", "value": "tel"}], "name": "input"}, new Set("textbox")],
          [{"attributes": [{"constraints": ["undefined"], "name": "list"}, {"name": "type", "value": "text"}], "name": "input"}, new Set("textbox")],
          [{"attributes": [{"constraints": ["undefined"], "name": "list"}, {"name": "type", "value": "url"}], "name": "input"}, new Set("textbox")],
          [{"name": "textarea"}, new Set("textbox")]
        ]
      )
    );
  });
});
